---
- hosts: all
  become: yes
  tasks:
    - name: Install EPEL repository
      dnf:
        name: epel-release
        state: present

    - name: Install Apache
      dnf:
        name: httpd
        state: present

    - name: Create index.html
      copy:
        dest: /var/www/html/index.html
        content: "Hello, world"
        owner: apache
        group: apache 
        mode: 0644

    - name: Chek Apache is running
      service:
        name: httpd
        state: started
        enabled: yes